[package]
name = "ntex-rt-macros"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "ntex runtime macros"
repository = "https://github.com/ntex-rs/ntex"
documentation = "https://docs.rs/ntex-rt-macros/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "^1"
syn = { version = "^1", features = ["full"] }

[dev-dependencies]
ntex = { version = "0.1.0" }
