[package]
name = "ntex-connect"
version = "0.3.0-beta.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntexwork connect utils for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-connect/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2021"

[lib]
name = "ntex_connect"
path = "src/lib.rs"

[features]
default = []

# openssl
openssl = ["tls-openssl", "ntex-tls/openssl"]

# rustls support
rustls = ["tls-rustls", "webpki-roots", "ntex-tls/rustls"]

# tokio runtime
tokio = ["ntex-rt/tokio", "ntex-tokio"]

# glommio runtime
glommio = ["ntex-rt/glommio", "ntex-glommio"]

# async-std runtime
async-std = ["ntex-rt/async-std", "ntex-async-std"]

[dependencies]
ntex-service = "1.2.0-beta.0"
ntex-bytes = "0.1.19"
ntex-http = "0.1.8"
ntex-io = "0.3.0-beta.0"
ntex-rt = "0.4.7"
ntex-tls = "0.3.0-beta.0"
ntex-util = "0.3.0-beta.0"
log = "0.4"
thiserror = "1.0"

ntex-tokio = { version = "0.3.0-beta.0", optional = true }
ntex-glommio = { version = "0.3.0-beta.0", optional = true }
ntex-async-std = { version = "0.3.0-beta.0", optional = true }

# openssl
tls-openssl = { version="0.10", package = "openssl", optional = true }

# rustls
tls-rustls = { version = "0.21", package = "rustls", optional = true }
webpki-roots = { version = "0.23", optional = true }

[dev-dependencies]
rand = "0.8"
env_logger = "0.10"
ntex = { version = "0.7.0-beta.0", features = ["tokio"] }
