[package]
name = "ntex-macros"
version = "0.1.3"
description = "ntex proc macros"
readme = "README.md"
authors = ["ntex contributors <team@ntex.rs>"]
license = "MIT"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "^1"
syn = { version = "^1", features = ["full", "parsing"] }
proc-macro2 = "^1"

[dev-dependencies]
ntex = { version = "0.7.0", features = ["tokio"] }
futures = "0.3"
env_logger = "0.10"