[package]
name = "ntex-io"
version = "2.16.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for abstracting io streams"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-io/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.83"

[lib]
name = "ntex_io"
path = "src/lib.rs"

[dependencies]
ntex-codec = "0.6"
ntex-bytes = "0.1.31"
ntex-util = "2.15"
ntex-service = "3.4"

bitflags = { workspace = true }
log = { workspace = true }
pin-project-lite = { workspace = true }

[dev-dependencies]
ntex = "2"
rand = { workspace = true }
