[package]
name = "ntex-io"
version = "1.0.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for encoding and decoding frames"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-io/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "ntex_io"
path = "src/lib.rs"

[dependencies]
ntex-codec = "0.6.2"
ntex-bytes = "0.1.24"
ntex-util = "1.0.0"
ntex-service = "2.0.0"

bitflags = "2.4"
log = "0.4"
pin-project-lite = "0.2"

[dev-dependencies]
rand = "0.8"
env_logger = "0.10"

ntex = { version = "1.0.0", features = ["tokio"] }
