[package]
name = "ntex-io"
version = "0.1.0-b.10"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for encoding and decoding frames"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-io/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_io"
path = "src/lib.rs"

[features]
default = ["tokio-traits"]

# tokio traits support
tokio-traits = ["tok-io/net", "tok-io/rt"]

# tokio runtime support
tokio = ["tok-io/net", "tok-io/rt"]

# async-std runtime support
async-std = ["async_std/unstable"]

[dependencies]
ntex-codec = "0.6.0"
ntex-bytes = "0.1.8"
ntex-util = "0.1.5"
ntex-service = "0.3.0-b.0"

bitflags = "1.3"
fxhash = "0.2.1"
log = "0.4"
pin-project-lite = "0.2"

tok-io = { version = "1", package = "tokio", default-features = false, optional = true }
async_std = { version = "1", package = "async-std", optional = true }

[dev-dependencies]
ntex = "0.5.0-b.5"
futures = "0.3"
rand = "0.8"
env_logger = "0.9"
