[package]
name = "ntex-service"
version = "0.1.5"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntex service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[dependencies]
futures-util = "0.3.13"
pin-project-lite = "0.2.4"

[dev-dependencies]
ntex-rt = "0.2"