[package]
name = "ntex-service"
version = "1.2.2"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntex service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2021"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[dependencies]
pin-project-lite = "0.2.6"
slab = "0.4"

[dev-dependencies]
ntex = { version = "0.7.0", features = ["tokio"] }
ntex-util = "0.3.0"
