[package]
name = "ntex-service"
version = "1.0.5"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-net.git"
documentation = "https://docs.rs/actix-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2018"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[dependencies]
futures-util = "0.3.1"
pin-project = "0.4.6"

[dev-dependencies]
actix-rt = "1.0.0"