[package]
name = "ntex-service"
version = "4.3.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntex service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[lints]
workspace = true

[features]
default = []

[dependencies]
log = { workspace = true }
slab = { workspace = true }
foldhash = { workspace = true }

[dev-dependencies]
ntex = { workspace = true }
