[package]
name = "ntex-service"
version = "3.3.2"
authors = ["ntex contributors <team@ntex.rs>"]
description = "ntex service"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-service/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "ntex_service"
path = "src/lib.rs"

[dependencies]
slab = "0.4"

[dev-dependencies]
ntex = "2"
ntex-util = "2"
