[package]
name = "ntex-util"
version = "0.3.4"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-util/"
categories = ["network-programming", "asynchronous"]
license = "MIT"
edition = "2021"

[lib]
name = "ntex_util"
path = "src/lib.rs"

[dependencies]
ntex-rt = "0.4.7"
ntex-service = "1.2.6"
bitflags = "2.4"
fxhash = "0.2.1"
log = "0.4"
slab = "0.4"
futures-timer = "3.0.2"
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
futures-sink = { version = "0.3", default-features = false, features = ["alloc"] }
pin-project-lite = "0.2.9"

[dev-dependencies]
ntex = { version = "0.7", features = ["tokio"] }
ntex-bytes = "0.1.18"
ntex-macros = "0.1.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
