[package]
name = "ntex-util"
version = "2.15.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Utilities for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-util/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.85"

[lib]
name = "ntex_util"
path = "src/lib.rs"

[dependencies]
ntex-bytes = "0.1"
ntex-service = "3.5"
ntex-rt = "0.4"

ahash = { workspace = true }
bitflags = { workspace = true }
log = { workspace = true }
slab = { workspace = true }
futures-timer = { workspace = true }
futures-core = { workspace = true }
pin-project-lite = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ntex = "2"
ntex-macros = "0.1.3"
futures-util = {workspace = true }
