[package]
name = "ntex-server"
version = "2.7.2"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Server for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-server/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "ntex_server"
path = "src/lib.rs"

[dependencies]
ntex-bytes = "0.1"
ntex-net = "2"
ntex-service = "3.4"
ntex-rt = "0.4"
ntex-util = "2.8"

async-channel = "2"
async-broadcast = "0.7"
core_affinity = "0.8"
polling = "3.3"
log = "0.4"
socket2 = "0.5"
oneshot = { version = "0.1", default-features = false, features = ["async"] }

[dev-dependencies]
ntex = "2"
ntex-macros = "0.1.3"

[target.'cfg(target_family = "unix")'.dependencies]
signal-hook = { version = "0.3", features=["iterator"] }

[target.'cfg(target_family = "windows")'.dependencies]
ctrlc = "3.4"
