[package]
name = "ntex-server"
version = "3.0.0-pre.2"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Server for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-server/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.85"

[lib]
name = "ntex_server"
path = "src/lib.rs"

[dependencies]
ntex-io = "3.0.0-pre.2"
ntex-net = "3.0.0-pre.2"
ntex-service = "3.6.2"
ntex-rt = "3"
ntex-util = "3"

async-channel = { workspace = true }
atomic-waker = { workspace = true }
core_affinity = { workspace = true }
oneshot = { workspace = true }
polling = { workspace = true }
log = { workspace = true }
socket2 = { workspace = true }

[dev-dependencies]
ntex = "3.0.0-pre.1"

[target.'cfg(target_family = "unix")'.dependencies]
signal-hook = { version = "0.3", features=["iterator"] }

[target.'cfg(target_family = "windows")'.dependencies]
ctrlc = "3.4"
