[package]
name = "ntex-server"
version = "3.6.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Server for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-server/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

[lib]
name = "ntex_server"
path = "src/lib.rs"

[dependencies]
ntex-io = { workspace = true }
ntex-net = { workspace = true }
ntex-service = { workspace = true }
ntex-rt = { workspace = true }
ntex-util = { workspace = true }
ntex-polling = { workspace = true }

async-channel = { workspace = true }
atomic-waker = { workspace = true }
core_affinity = { workspace = true }
oneshot = { workspace = true }
log = { workspace = true }
socket2 = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
ntex = { workspace = true }

[target.'cfg(target_family = "unix")'.dependencies]
signal-hook = { workspace = true, features=["iterator"] }

[target.'cfg(target_family = "windows")'.dependencies]
ctrlc = { workspace = true }
