[package]
name = "ntex-server"
version = "0.1.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Server for ntex framework"
keywords = ["network", "framework", "async", "futures"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex.git"
documentation = "https://docs.rs/ntex-server/"
categories = ["network-programming", "asynchronous"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
name = "ntex_server"
path = "src/lib.rs"

[dependencies]
ntex-bytes = "0.1"
ntex-service = "2.0"
ntex-rt = "0.4"
ntex-util = "1.0"

async-channel = "2.2"
async-broadcast = "0.7"
log = "0.4"
signal-hook = { version = "0.3", features=["extended-siginfo"] }
oneshot = { version = "0.1", default-features = false, features = ["async"] }

[dev-dependencies]
ntex = { version = "1", features = ["tokio"] }
ntex-macros = "0.1.3"
